/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    KeywordBarChart: typeof import('./src/components/charts/KeywordBarChart.vue')['default']
    KpiCard: typeof import('./src/components/common/KpiCard.vue')['default']
    LoadingCard: typeof import('./src/components/common/LoadingCard.vue')['default']
    NetworkForceGraph: typeof import('./src/components/charts/NetworkForceGraph.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/common/SectionHeader.vue')['default']
    SentimentBarChart: typeof import('./src/components/charts/SentimentBarChart.vue')['default']
    SentimentPieChart: typeof import('./src/components/charts/SentimentPieChart.vue')['default']
    StatCard: typeof import('./src/components/common/StatCard.vue')['default']
    TopicBubbleChart: typeof import('./src/components/charts/TopicBubbleChart.vue')['default']
    TopicCard: typeof import('./src/components/common/TopicCard.vue')['default']
    TopicDrawer: typeof import('./src/components/common/TopicDrawer.vue')['default']
    TopicSentimentHeatmap: typeof import('./src/components/charts/TopicSentimentHeatmap.vue')['default']
    TrendLineChart: typeof import('./src/components/charts/TrendLineChart.vue')['default']
    WordCloudChart: typeof import('./src/components/charts/WordCloudChart.vue')['default']
  }
}
